{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tensafe.fullname" . }}
  labels:
    {{- include "tensafe.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "tensafe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
